POST http://localhost:3000/api/items/{pizzaItemId}/addons
Content-Type: application/json

{
  "name": "BBQ Sauce",
  "price": 20,
  "group_name": "Sauces",
  "group_selection_type": "single",
  "max_selections": 1
}